# Generated by Django 3.2.4 on 2021-12-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('scopes', '0007_alter_speciescommunity_picture'),
        ('user_functions', '0007_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ProjectContributors',
            field=models.ManyToManyField(to='user_functions.Contributor'),
        ),
        migrations.AddField(
            model_name='project',
            name='RelatedProjects',
            field=models.ManyToManyField(to='projects.RelatedProject'),
        ),
        migrations.AddField(
            model_name='project',
            name='SpeComs',
            field=models.ManyToManyField(through='projects.SpeCom2Project', to='scopes.SpeciesCommunity'),
        ),
        migrations.AddField(
            model_name='project',
            name='Triggers',
            field=models.ManyToManyField(to='projects.Trigger'),
        ),
        migrations.AddField(
            model_name='objective2step',
            name='ObjectiveID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.objective'),
        ),
        migrations.AddField(
            model_name='objective2step',
            name='StepID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.step'),
        ),
        migrations.AddField(
            model_name='objective',
            name='Milestones',
            field=models.ManyToManyField(to='projects.Milestone'),
        ),
        migrations.AddField(
            model_name='objective',
            name='ProjectID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='objective',
            name='Steps',
            field=models.ManyToManyField(through='projects.Objective2Step', to='projects.Step'),
        ),
        migrations.AddField(
            model_name='milestoneprogress',
            name='MilestoneID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='MilestoneProgress',
            field=models.ManyToManyField(to='projects.MilestoneProgress'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='ObjectiveID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.objective'),
        ),
        migrations.AddField(
            model_name='method2protocol',
            name='MethodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.method'),
        ),
        migrations.AddField(
            model_name='method2protocol',
            name='ProtocolID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.protocol'),
        ),
        migrations.AddField(
            model_name='method',
            name='Protocols',
            field=models.ManyToManyField(through='projects.Method2Protocol', to='projects.Protocol'),
        ),
        migrations.AddField(
            model_name='location2project',
            name='LocationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopes.location'),
        ),
        migrations.AddField(
            model_name='location2project',
            name='ProjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='goal2project',
            name='GoalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopes.goal'),
        ),
        migrations.AddField(
            model_name='goal2project',
            name='ProjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='conmeas2project',
            name='ConMeasID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scopes.conservationmeasure'),
        ),
        migrations.AddField(
            model_name='conmeas2project',
            name='ProjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
