# Generated by Django 3.2.4 on 2021-12-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211214_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='ProposedResponse',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='TriggerDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='TriggerIndicators',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='TriggerName',
            field=models.CharField(max_length=38, null=True),
        ),
    ]
