# Generated by Django 3.2.4 on 2021-12-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20211215_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='ObjectiveID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.objective'),
        ),
        migrations.AlterField(
            model_name='milestoneprogress',
            name='MilestoneID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.milestone'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='ProjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='relatedproject',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='ProjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='triggerstatus',
            name='TriggerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.trigger'),
        ),
    ]
