# Generated by Django 3.2.4 on 2021-12-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0007_alter_speciescommunity_picture'),
        ('user_functions', '0007_contributor'),
        ('projects', '0007_auto_20211217_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='Protocols',
        ),
        migrations.AddField(
            model_name='method',
            name='Protocols',
            field=models.ManyToManyField(through='projects.Method2Protocol', to='projects.Protocol'),
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='MilestoneProgress',
        ),
        migrations.AddField(
            model_name='milestone',
            name='MilestoneProgress',
            field=models.ManyToManyField(to='projects.MilestoneProgress'),
        ),
        migrations.RemoveField(
            model_name='objective',
            name='Milestones',
        ),
        migrations.AddField(
            model_name='objective',
            name='Milestones',
            field=models.ManyToManyField(to='projects.Milestone'),
        ),
        migrations.RemoveField(
            model_name='objective',
            name='Steps',
        ),
        migrations.AddField(
            model_name='objective',
            name='Steps',
            field=models.ManyToManyField(through='projects.Objective2Step', to='projects.Step'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='ConMeas',
        ),
        migrations.AddField(
            model_name='project',
            name='ConMeas',
            field=models.ManyToManyField(through='projects.ConMeas2Project', to='scopes.ConservationMeasure'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='Goals',
        ),
        migrations.AddField(
            model_name='project',
            name='Goals',
            field=models.ManyToManyField(through='projects.Goal2Project', to='scopes.Goal'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='Locations',
        ),
        migrations.AddField(
            model_name='project',
            name='Locations',
            field=models.ManyToManyField(through='projects.Location2Project', to='scopes.Location'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='Objectives',
        ),
        migrations.AddField(
            model_name='project',
            name='Objectives',
            field=models.ManyToManyField(to='projects.Objective'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='Outputs',
        ),
        migrations.AddField(
            model_name='project',
            name='Outputs',
            field=models.ManyToManyField(to='projects.Output'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='People',
        ),
        migrations.AddField(
            model_name='project',
            name='People',
            field=models.ManyToManyField(to='user_functions.Person'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='ProjectContributors',
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectContributors',
            field=models.ManyToManyField(to='user_functions.Contributor'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='RelatedProjects',
        ),
        migrations.AddField(
            model_name='project',
            name='RelatedProjects',
            field=models.ManyToManyField(to='projects.RelatedProject'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='SpeComs',
        ),
        migrations.AddField(
            model_name='project',
            name='SpeComs',
            field=models.ManyToManyField(through='projects.SpeCom2Project', to='scopes.SpeciesCommunity'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='Triggers',
        ),
        migrations.AddField(
            model_name='project',
            name='Triggers',
            field=models.ManyToManyField(to='projects.Trigger'),
        ),
        migrations.RemoveField(
            model_name='step',
            name='Methods',
        ),
        migrations.AddField(
            model_name='step',
            name='Methods',
            field=models.ManyToManyField(through='projects.Step2Method', to='projects.Method'),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='TriggerStatus',
        ),
        migrations.AddField(
            model_name='trigger',
            name='TriggerStatus',
            field=models.ManyToManyField(to='projects.TriggerStatus'),
        ),
    ]
