# Generated by Django 3.2.4 on 2022-01-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20211217_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='ProjectID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
