# Generated by Django 3.2.4 on 2022-01-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_output_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='OutputAuthors',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='OutputCitation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='OutputConstraints',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='OutputDOI',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='OutputDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='OutputDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='OutputTitle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='OutputType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='OutputURI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='OutputVersion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
