# Generated by Django 3.2.4 on 2022-01-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20220113_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='ObjCode',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='ObjDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='ObjEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='ObjFlowDiagram',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='ObjName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='ObjStartDate',
            field=models.DateField(null=True),
        ),
    ]
