# Generated by Django 3.2.4 on 2022-01-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20220121_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='StepID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.step'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='MethodID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.method'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='ObjectiveID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.objective'),
            preserve_default=False,
        ),
    ]
