# Generated by Django 3.2.4 on 2022-01-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20220124_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='MethodCode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='MethodContact',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='MethodDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='MethodDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='MethodTitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='MethodType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='MethodVersion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='ProtocolAuthor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='ProtocolDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='ProtocolDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='ProtocolLink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='ProtocolTitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='ProtocolVerision',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='StepCode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='StepDependencies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='StepEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='StepName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='StepStartDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='StepSummary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='StepType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
