# Generated by Django 3.2.4 on 2021-10-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMCode', models.CharField(max_length=10)),
                ('CMDescription', models.CharField(max_length=100)),
                ('SppHab', models.CharField(max_length=100)),
                ('CMType', models.CharField(max_length=50)),
                ('CMSummary', models.TextField()),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoalName', models.CharField(max_length=255)),
                ('GoalType', models.CharField(max_length=50)),
                ('GoalDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationCode', models.CharField(max_length=10)),
                ('LocationName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('SpatialLayer', models.TextField()),
                ('SpatialID', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TargetType', models.CharField(choices=[('Species', 'Species'), ('Ecological Comunity', 'Ecological Comunity')], max_length=25)),
                ('Acronym', models.CharField(max_length=10)),
                ('CommonName', models.CharField(max_length=255)),
                ('ScientificName', models.CharField(max_length=255)),
                ('ITISTSN', models.CharField(max_length=8)),
                ('CommunityName', models.CharField(max_length=255)),
                ('Synonyms', models.TextField()),
                ('Comments', models.TextField()),
                ('Picture', models.ImageField(upload_to='static path')),
            ],
        ),
    ]
