# Generated by Django 3.2.4 on 2021-10-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciescommunity',
            name='Picture',
        ),
    ]
