# Generated by Django 3.2.4 on 2021-10-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0002_remove_speciescommunity_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciescommunity',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='speciescommunity',
            name='Synonyms',
        ),
    ]
