# Generated by Django 3.2.4 on 2021-10-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0003_auto_20211011_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciescommunity',
            name='Comments',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciescommunity',
            name='Picture',
            field=models.ImageField(default='null', upload_to='AIMS\\static'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciescommunity',
            name='Synonyms',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
