# Generated by Django 3.2.4 on 2021-10-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0004_auto_20211011_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciescommunity',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='AIMS\\static'),
        ),
    ]
