# Generated by Django 3.2.4 on 2021-10-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0005_alter_speciescommunity_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciescommunity',
            name='Picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
