# Generated by Django 3.2.4 on 2021-08-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('Affiliation', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Level', models.CharField(choices=[('Authorized', 'Authorized'), ('Lead', 'Lead'), ('Admin', 'Admin')], max_length=12)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Authorized', 'Authorized'), ('Lead', 'Lead'), ('Admin', 'Admin')], default='Unlocked', max_length=10)),
                ('Person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_functions.person')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('ContactID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_functions.person')),
            ],
        ),
    ]
