# Generated by Django 3.2.4 on 2021-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_functions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(choices=[('Unlocked', 'Unlocked'), ('Locked', 'Locked')], default='Unlocked', max_length=10),
        ),
    ]
