# Generated by Django 3.2.4 on 2021-09-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_functions', '0003_auto_20210903_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Level', models.CharField(choices=[('Authorized', 'Authorized'), ('Lead', 'Lead'), ('Admin', 'Admin')], max_length=12)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Unlocked', 'Unlocked'), ('Locked', 'Locked')], default='Unlocked', max_length=10)),
                ('Person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_functions.person')),
            ],
        ),
        migrations.DeleteModel(
            name='UserSuplement',
        ),
    ]
