# Generated by Django 3.2.4 on 2021-09-03 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_functions', '0004_auto_20210903_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(choices=[('Authorized', 'Authorized'), ('Lead', 'Lead'), ('Admin', 'Admin')], max_length=12)),
                ('Status', models.CharField(choices=[('Unlocked', 'Unlocked'), ('Locked', 'Locked')], default='Unlocked', max_length=10)),
                ('Person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_functions.person')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
