# Generated by Django 3.2.4 on 2024-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtemplate',
            name='file',
            field=models.FileField(null=True, upload_to='reports/'),
        ),
    ]
