# Generated by Django 3.2.4 on 2024-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_customtemplate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtemplate',
            name='file',
            field=models.FileField(upload_to='reports/'),
        ),
    ]
