# Generated by Django 3.2.4 on 2024-08-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_customtemplate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplate',
            name='name',
            field=models.CharField(default='User Generated', max_length=255),
        ),
    ]
